### ISSUE TITLE
.fullscreen class on HTML conflicts with Modernizr

### ISSUE THREAD

**Issue by Grawl** [artpolikarpov/fotorama#449]
Simple: I want to use **both** pre-packed full [Modernizr](http://modernizr.com) installed from [modernizr-min](https://github.com/chatii2412/modernizr-min) and Fotorama.

But there is a problem: Modernizr adds class `.fullscreen` on `HTML` and Fotorama styles it:

``` css
.fullscreen {
width: 100% !important;
height: 100% !important;
max-width: 100% !important;
max-height: 100% !important;
margin: 0 !important;
padding: 0 !important;
overflow: hidden !important;
background: #000
}
```

Not good.

Better to use `.fotorama__body--fullscreen` class in Fotorama.
