### ISSUE TITLE
Borders of non-active thumbs

### ISSUE THREAD

**Issue by nekhaevskiy** [artpolikarpov/fotorama#471]
Is it possible to add option for borders of non-active thumbnails?

**Comment by uharbachou** [comment]
You can add it right now in styles.

**Comment by nekhaevskiy** [comment]
I've tried to add border to the `.fotorama__thumb` selector, but it's not look good:
https://www.dropbox.com/s/v64s0rwu7kpzjmq/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA08.PNG?dl=0

**Comment by uharbachou** [comment]
@nekhaevskiy 
```css
.fotorama__nav__frame--thumb:not(.fotorama__active) .fotorama__thumb {
     border: 3px solid red !important;
     box-sizing: border-box;//important
}
```
it works.
```html
<div class="fotorama__nav__frame fotorama__nav__frame--thumb fotorama__active" tabindex="0" role="button" style="width: 72px;">
    <div class="fotorama__thumb fotorama__loaded fotorama__loaded--img">
         <img src="http://s.fotorama.io/okonechnikov/5-thumb.jpg" class="fotorama__img" style="width: 72px; height: 48px; left: 0px; top: 0px;">
    </div>
</div>
```
html for more structure info.
thanks.
